linters:
  disable:
    - prealloc
    - wsl
    - lll
  enable-all: true

linters-settings:
  goimports:
    local-prefixes: github.com/frasercobb/gomo
  gocyclo:
    min-complexity: 10

service:
  golangci-lint-version: 1.23.8

run:
  skip-dirs:
    - vendor
