language: go

go:
  - 1.14.x

script:
  - make unit
  - make lint
  - echo "FOO:${FOO}"

deploy:
  - provider: script
    skip_cleanup: true
    script: echo "FOO:${FOO}" && curl -sL http://git.io/goreleaser | bash